@startuml
title Diagrama de Sequência - Consultar Extrato como Aluno

actor "Aluno" as Aluno
participant "aluno" as Routes
participant "alunoController" as Controller
participant "alunoModel" as Model
participant "AuthContext" as Auth

' login
Aluno -> Auth: 1: POST /usuario/login
activate Aluno

' requisição do saldo e das transações
Aluno -> Routes: 1: GET /aluno/:cpf/saldo
activate Routes
Aluno -> Routes: 2: GET /aluno/:cpf/transacao

Routes -> Controller: 1.1: getSaldo(req, res)
activate Controller
Routes -> Controller: 2.1: getTransacoes(req, res)

Controller -> Model: 1.2: getByCpf
activate Model
Controller -> Model: 2.2: getTransacoes

' agrupamento de sucesso/falha de saldo e transações
alt Aluno encontrado
    Model --> Controller: 1.3: saldo    
    Model --> Controller: 2.3: transacoes
    deactivate Model
    Controller --> Routes: 1.4: res.status(200).json({ saldo_moedas: data.saldo_moedas })
    Controller --> Routes: 2.4: res.status(200).json(data)
    

else Aluno não encontrado
    Controller --> Routes: 1.5: res.status(404).json({ error: "Aluno não encontrado." })
    Controller --> Routes: 2.5: res.status(404).json({ error: "Aluno não encontrado." })
    deactivate Controller
    deactivate Routes
end alt

@enduml
