@startuml
skinparam linestyle ortho
Actor "Aluno" as aluno
rectangle "<u> :empresaParceira" as routes
rectangle "<u> :empresaParceiraController" as controller
rectangle "empresaParceiraModel" as model

aluno -right-> routes: 1 GET/empresa/vantagens/todas 
routes -right-> controller: 1.1 getAllVantagens(req, res) 
controller -right-> model: 1.1.1 getAllVantagens()
@enduml