@startuml
skinparam linestyle ortho
actor "Aluno" as aluno
rectangle "<u> alunoRoutes" as routes
rectangle "<u> alunoController" as controller
rectangle "<u> alunoModel" as model

aluno -right-> routes: 1.1 POST/resgatar-vantagem/:cpf 
routes -right-> controller: 1.2 resgatarVantagem(req, res) 
controller -right-> model: 1.3 resgatarVantagem(cpf, idVantagem) 
model -left-> controller: 1.4 {success: true, novoSaldo}
controller -left-> routes:  1.5 res.status(200).json(data)
@enduml
